# Generated by Django 5.0.4 on 2024-04-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserJoinTripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelplanning.tripplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('tripplan', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='JoinTripPlan',
        ),
    ]
