# Generated by Django 5.0.4 on 2024-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0002_tripplan_user_userjointripplan_delete_jointripplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='title',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
