# Generated by Django 5.0.4 on 2024-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0003_tripplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuser',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
