# Generated by Django 5.0.4 on 2024-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0004_alter_reportuser_title_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='startLocation',
            field=models.CharField(max_length=100),
        ),
    ]
