# Generated by Django 5.0.4 on 2024-04-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0006_trip_image_delete_tripimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tripplan',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
