# Generated by Django 5.0.4 on 2024-04-20 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0008_comment_tripplan_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
