# Generated by Django 5.0.4 on 2024-04-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0009_alter_trip_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='reportuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tripplan',
            options={'ordering': ['-id']},
        ),
    ]
