# Generated by Django 5.0.4 on 2024-05-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplanning', '0010_alter_comment_options_alter_reportuser_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('tripplan', 'destination')},
        ),
    ]
